### ISSUE TITLE
Should hide before/after dates be ignored when previewing?

### ISSUE THREAD

**Issue by adamschwartz** [EagerApps/SnowPro#1]
I found it a little confusing that once I checked “Hide the snow before a specific date” I no longer saw the snow. I think while previewing we should probably always show the snow, and maybe add a note to explain this, possibly with a `help` option which `showIf`s when one or more of the date constraint checkboxes is checked.

@zackbloom

**Comment by zackbloom** [comment]
Done

**Comment by adamschwartz** [comment]
:+1: thx!
